# Generated by Django 5.1 on 2024-08-31 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 to 15 digits and numeric.', regex='^\\d{10,15}$'), django.core.validators.MinLengthValidator(10, 'Phone number must be at least 10 digits.')]),
        ),
    ]
